-- Run in Supabase SQL Editor after creating a project. Then run the migrations in
-- supabase/migrations, including the multi-user workspace/RLS migration.
create type public.product_visibility as enum ('workspace', 'agent', 'marketplace');
create table public.companies (id uuid primary key default gen_random_uuid(), owner_id uuid references auth.users(id), name text not null, bin text, city text, phone text, created_at timestamptz default now());
create table public.products (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, name text not null, sku text, price numeric(12,2) not null default 0, stock integer not null default 0, commission_rate numeric(5,2) not null default 0, workspace_active boolean not null default true, agent_visible boolean not null default false, marketplace_published boolean not null default false, created_at timestamptz default now());
create table public.sales_agents (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id), full_name text not null, phone text, created_at timestamptz default now());
create table public.company_agents (company_id uuid references public.companies(id) on delete cascade, agent_id uuid references public.sales_agents(id) on delete cascade, status text not null default 'pending', primary key(company_id, agent_id));
create table public.stores (id uuid primary key default gen_random_uuid(), company_id uuid references public.companies(id), name text not null, address text, contact_name text, phone text, created_at timestamptz default now());
create table public.orders (id uuid primary key default gen_random_uuid(), company_id uuid references public.companies(id), store_id uuid references public.stores(id), agent_id uuid references public.sales_agents(id), status text not null default 'draft', warehouse_status text not null default 'new', total numeric(12,2) not null default 0, accepted_at timestamptz, picking_started_at timestamptz, ready_at timestamptz, labeled_at timestamptz, shipped_at timestamptz, sticker_code text, waybill_number text, created_at timestamptz default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid references public.orders(id) on delete cascade, product_id uuid references public.products(id), quantity integer not null, unit_price numeric(12,2) not null, commission_amount numeric(12,2) not null default 0);
