"use client";

import { useState } from "react";
import RouteMap from "../../components/RouteMap";

type Screen = "dashboard" | "orders" | "detail" | "route" | "stops" | "scanner" | "done" | "reports" | "notifications" | "vehicle" | "profile" | "fuel" | "documents" | "support" | "more";
type Stop = { name: string; address: string; time: string; distance: string; status: "Жолда" | "Күтуде" | "Жоспарда" | "Жеткізілді"; coordinates: [number, number] };

const stops: Stop[] = [
  { name: "Строймаг", address: "Алматы қ., Райымбек 348", time: "10:30", distance: "2.4 км", status: "Жолда", coordinates: [76.8897, 43.2383] },
  { name: "ЭлектроДом", address: "Алматы қ., Төле би 215", time: "11:15", distance: "5.7 км", status: "Жолда", coordinates: [76.912, 43.256] },
  { name: "Техносвет", address: "Алматы қ., Абай 68", time: "12:00", distance: "3.2 км", status: "Күтуде", coordinates: [76.905, 43.225] },
  { name: "Светлый дом", address: "Алматы қ., Сайын 22", time: "13:00", distance: "4.1 км", status: "Жоспарда", coordinates: [76.87, 43.245] },
  { name: "1000 Мелочей", address: "Алматы қ., Жетысу 12", time: "14:00", distance: "6.8 км", status: "Жоспарда", coordinates: [76.93, 43.27] },
  { name: "ПромЭлектро", address: "Алматы қ., Бауыpжан 45", time: "15:00", distance: "7.9 км", status: "Жоспарда", coordinates: [76.85, 43.22] },
];
const money = (value: number) => `${value.toLocaleString("kk-KZ")} ₸`;

export default function DispatcherApp() {
  const [screen, setScreen] = useState<Screen>("dashboard");
  const [logged, setLogged] = useState(false);
  const [selectedStop, setSelectedStop] = useState(stops[0]);
  const [delivered, setDelivered] = useState(false);
  if (!logged) return <DispatcherLoginAlsat onLogin={() => setLogged(true)} />;
  const go = (next: Screen) => setScreen(next);
  return <main className="qmart-role dispatcher-shell">
    <header className="role-header"><button onClick={() => go("more")}>☰</button><div><b>ALSAT</b><small>ЭКСПЕДИТОР</small></div><button onClick={() => go("notifications")}>♧</button></header>
    {screen === "dashboard" && <DispatcherDashboard go={go} />}
    {screen === "orders" && <DispatcherOrders go={go} onSelect={() => go("detail")} />}
    {screen === "detail" && <DispatcherDetail stop={selectedStop} delivered={delivered} go={go} onDeliver={() => { setDelivered(true); go("done"); }} />}
    {screen === "route" && <DispatcherRoute go={go} onSelect={(stop) => { setSelectedStop(stop); go("detail"); }} />}
    {screen === "stops" && <StopList go={go} onSelect={(stop) => { setSelectedStop(stop); go("detail"); }} />}
    {screen === "scanner" && <BarcodeScanner go={go} />}
    {screen === "done" && <DeliveryDone stop={selectedStop} go={go} />}
    {screen === "reports" && <DispatcherReports go={go} />}
    {screen === "notifications" && <Notifications go={go} />}
    {screen === "vehicle" && <Vehicle go={go} />}
    {screen === "profile" && <DispatcherProfile go={go} />}
    {screen === "fuel" && <Fuel go={go} />}
    {screen === "documents" && <Documents go={go} />}
    {screen === "support" && <Support go={go} />}
    {screen === "more" && <DispatcherMore go={go} />}
    <nav className="role-bottom"><button className={screen === "dashboard" ? "active" : ""} onClick={() => go("dashboard")}>⌂<small>Басты</small></button><button className={screen === "orders" || screen === "detail" || screen === "done" ? "active" : ""} onClick={() => go("orders")}>▤<small>Тапсырыс</small></button><button className={screen === "route" || screen === "stops" ? "active" : ""} onClick={() => go("route")}>⌖<small>Маршрут</small></button><button className={screen === "notifications" ? "active" : ""} onClick={() => go("notifications")}>♧<small>Хабарлама</small></button><button className={screen === "profile" || screen === "more" ? "active" : ""} onClick={() => go("profile")}>♙<small>Профиль</small></button></nav>
  </main>;
}

function DispatcherLoginAlsat({ onLogin }: { onLogin: () => void }) { return <main className="role-login dispatcher-login"><div className="role-login-brand"><span>A</span><b>ALSAT</b><small>ЭКСПЕДИТОР</small></div><div className="truck-illustration">🚚</div><h1>Жеткізу процесін<br/>басқарыңыз!</h1><p>Тапсырыстарды жеткізіп, маршруттарды бақылаңыз, статусын жаңартыңыз.</p><div className="role-benefits"><span>▣　Жеткізуге арналған барлық құралдар</span><span>⌖　Маршрут және навигация</span><span>▥　Статистика және есептер</span><span>♧　Онлайн байланыс</span></div><label>Телефон нөмірі<input placeholder="+7 (___) ___-__-__" inputMode="tel"/></label><button className="role-primary" onClick={onLogin}>Кіру</button><button className="role-secondary" onClick={onLogin}>▣　SMS арқылы кіру</button><small className="role-offline">◉　Offline режимі қолжетімді</small></main> }

function DispatcherLogin({ onLogin }: { onLogin: () => void }) { return <main className="role-login dispatcher-login"><div className="role-login-brand"><span>Q</span><b>QMART</b><small>ЭКСПЕДИТОР</small></div><div className="truck-illustration">🚚</div><h1>Жеткізу процесін<br/>басқарыңыз!</h1><p>Тапсырыстарды жеткізіп, маршруттарды бақылаңыз, статусын жаңартыңыз.</p><div className="role-benefits"><span>▣　Жеткізуге арналған барлық құралдар</span><span>⌖　Маршрут және навигация</span><span>▥　Статистика және есептер</span><span>♧　Онлайн байланыс</span></div><label>Телефон нөмірі<input placeholder="+7 (___) ___-__-__" inputMode="tel"/></label><button className="role-primary" onClick={onLogin}>Кіру</button><button className="role-secondary" onClick={onLogin}>▣　SMS арқылы кіру</button><small className="role-offline">◉　Offline режимі қолжетімді</small></main> }
function DispatcherDashboard({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-profile"><span className="role-avatar">НӘ</span><div><strong>Сәлеметсіз бе,<br/>Нұрлан!</strong><small>Экспедитор</small></div><button onClick={() => go("notifications")}>♧</button></div><section className="role-metrics"><small>Бүгінгі көрсеткіштер</small><p>12 мамыр, жексенбі</p><div><span>Жеткізуге арналған<strong>12</strong><em>тапсырыс</em></span><span>Жеткізілді<strong>8</strong><em>тапсырыс</em></span><span>Жолда<strong>3</strong><em>тапсырыс</em></span><span>Кешіктіру<strong>1</strong><em>тапсырыс</em></span></div></section><div className="role-section-title"><h3>Бүгінгі жоспар</h3><button onClick={() => go("route")}>Толығырақ ›</button></div><div className="plan-card"><div><b>12</b><small>тоқтау нүктесі</small></div><div><b>245 км</b><small>жалпы қашықтық</small></div><div><b>8 сағ 40 мин</b><small>жоспарланған уақыт</small></div><div><b>75%</b><small>орындалды</small></div><i><span style={{ width: "75%" }}/></i></div><div className="role-section-title"><h3>Соңғы тапсырыс</h3><button onClick={() => go("orders")}>Барлығын көру ›</button></div><button className="role-order-mini" onClick={() => go("detail")}><span>▣</span><div><strong>№100045 · Строймаг</strong><small>Алматы қ., Райымбек 348<br/>10:30 дейін жеткізу</small></div><em>Жолда</em></button></section> }
function DispatcherOrders({ go, onSelect }: { go: (screen: Screen) => void; onSelect: () => void }) { const [filter, setFilter] = useState("all"); const visible = filter === "all" ? stops : stops.filter((stop) => filter === "Жолда" ? stop.status === "Жолда" : filter === "Жоспар" ? stop.status === "Жоспарда" : stop.status === "Күтуде"); return <section className="role-screen"><div className="role-heading"><h1>Тапсырыстар</h1><button onClick={() => go("scanner")}>⌁</button></div><div className="role-tabs"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>Барлығы 12</button><button className={filter === "Жолда" ? "active" : ""} onClick={() => setFilter("Жолда")}>Жолда 3</button><button className={filter === "Күтуде" ? "active" : ""} onClick={() => setFilter("Күтуде")}>Күтуде 3</button><button className={filter === "Жоспар" ? "active" : ""} onClick={() => setFilter("Жоспар")}>Жоспарда 8</button></div>{visible.map((stop, i) => <button className="role-list-row" key={stop.name} onClick={onSelect}><span className="list-icon">♧</span><div><strong>№{100045 + i} · {stop.name}</strong><small>{stop.address}<br/>{stop.time} дейін</small></div><div className="role-row-right"><em className={`status ${stop.status === "Жолда" ? "green" : stop.status === "Күтуде" ? "yellow" : "blue"}`}>{stop.status}</em></div></button>)}</section> }
function DispatcherDetail({ stop, delivered, go, onDeliver }: { stop: Stop; delivered: boolean; go: (screen: Screen) => void; onDeliver: () => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("orders")}>‹</button><h1>Тапсырыс {"№100045"}</h1><button>⌯</button></div><span className="status green">{delivered ? "Жеткізілді" : stop.status}</span><div className="detail-card"><small>Клиент</small><strong>{stop.name}</strong><small>Мекенжайы</small><b>{stop.address}</b><small>Байланыс тұлға</small><b>Алексей · +7 777 123 45 67</b></div><div className="detail-card"><small>Жеткізу уақыты</small><b>Бүгін, {stop.time} дейін</b><small>Төлем түрі</small><b>Несие (14 күн)</b></div><div className="role-section-title"><h3>Тауарлар (3)</h3><button>Барлығы</button></div><div className="detail-card product-lines"><span>◌　KRAUSZ Шам A60 12W E27 <b>10 × 650 ₸</b></span><span>◌　KRAUSZ Проектор 100W <b>2 × 8 500 ₸</b></span><span>◌　KRAUSZ Панель LED 36W <b>5 × 4 200 ₸</b></span><strong>Жалпы сома <b>44 500 ₸</b></strong></div>{delivered ? <button className="role-primary" onClick={() => go("orders")}>Тапсырыстар тізіміне қайту</button> : <button className="role-primary" onClick={onDeliver}>Жеткізілді деп белгілеу</button>}</section> }
function DispatcherRoute({ go, onSelect }: { go: (screen: Screen) => void; onSelect: (stop: Stop) => void }) { return <section className="role-screen"><div className="role-heading"><h1>Бүгінгі маршрут</h1><button onClick={() => go("stops")}>☷</button></div><p className="role-muted">12 тоқтау нүктесі · 245 км</p><RouteMap stops={stops.map((stop) => ({ name: stop.name, coordinates: stop.coordinates }))}/><div className="next-stop"><small>Келесі тоқтау</small><strong>№100045 Строймаг</strong><span>Райымбек 348 · 10:30 дейін · 2.4 км</span><button onClick={() => onSelect(stops[0])}>Навигация</button></div><div className="route-stop-list">{stops.slice(0, 4).map((stop, index) => <button className="role-list-row" key={stop.name} onClick={() => onSelect(stop)}><span className="stop-number">{index + 1}</span><div><strong>{stop.name}</strong><small>{stop.time} дейін · {stop.distance}</small></div><em className={`status ${stop.status === "Жолда" ? "green" : stop.status === "Күтуде" ? "yellow" : "blue"}`}>{stop.status}</em></button>)}</div></section> }
function StopList({ go, onSelect }: { go: (screen: Screen) => void; onSelect: (stop: Stop) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("route")}>‹</button><h1>Тоқтау нүктелері</h1><button>⌖</button></div><div className="role-tabs"><button className="active">Барлығы</button><button>Жоспар</button><button>Аяқталды</button></div>{stops.map((stop, index) => <button className="role-list-row" key={stop.name} onClick={() => onSelect(stop)}><span className={`stop-number ${index < 2 ? "complete" : ""}`}>{index + 1}</span><div><strong>№{100045 + index}　{stop.name}</strong><small>{stop.time} дейін · {stop.distance}</small></div><em className={`status ${stop.status === "Жолда" ? "green" : stop.status === "Күтуде" ? "yellow" : "blue"}`}>{stop.status}</em></button>)}</section> }
function BarcodeScanner({ go }: { go: (screen: Screen) => void }) { const [code, setCode] = useState(""); return <section className="role-screen scanner-screen"><div className="role-heading"><button className="back" onClick={() => go("orders")}>‹</button><h1>Штрихкодты сканерлеу</h1><button onClick={() => go("orders")}>×</button></div><div className="scanner-box"><div className="scan-corners">▣</div><p>Штрихкодты рамкаға орналастырыңыз</p></div><small className="role-muted center">немесе кодты қолмен енгізу</small><input className="role-input" value={code} onChange={(event) => setCode(event.target.value)} placeholder="Штрихкод енгізу　⌕"/><div className="scanner-actions"><button>♨<small>Фонарик</small></button><button>▧<small>Галерея</small></button></div><button className="role-primary" onClick={() => go("detail")}>Тексеру</button></section> }
function DeliveryDone({ stop, go }: { stop: Stop; go: (screen: Screen) => void }) { return <section className="role-screen done-screen"><span className="big-check">✓</span><h1>Тапсырыс сәтті жеткізілді!</h1><p>№100045 · {stop.name}<br/>{stop.address}</p><div className="signature-box">Клиент қолтаңбасы<div>✍</div></div><button className="role-primary" onClick={() => go("orders")}>Растау және келесіге өту</button><button className="text-button" onClick={() => go("orders")}>Тапсырыстар тізіміне қайту</button></section> }
function DispatcherReports({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><h1>Есеп</h1><button>2024 · 12 мамыр⌄</button></div><section className="report-hero role-report"><small>Көрсеткіштер</small><div><span>Жеткізілді<strong>8</strong></span><span>Кешіктіру<strong>1</strong></span><span>Қашықтық<strong>245 км</strong></span><span>Уақыт<strong>8 сағ 40 мин</strong></span></div></section><div className="role-section-title"><h3>Есептер</h3></div>{["Күнделікті есеп", "Апталық есеп", "Айлық есеп", "Тапсырыстар бойынша есеп"].map((name) => <button className="setting-row role-setting" key={name} onClick={() => go("documents")}>▣　{name}<b>›</b></button>)}</section> }
function Notifications({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><h1>Хабарламалар</h1><button onClick={() => go("more")}>•••</button></div><div className="role-tabs"><button className="active">Барлығы</button><button>Оқылмаған <i>2</i></button></div>{["Жаңа тапсырыс қосылды", "Диспетчер", "Клиент: ЭлектроДом", "Жүйе хабарламасы"].map((name, index) => <div className="notification-row" key={name}><span className={`notification-icon n${index}`}>♧</span><div><strong>{name}</strong><small>{index === 0 ? "№100045 тапсырысы қосылды" : index === 1 ? "Ертеңгі маршрут дайын" : "Клиент сізге хабарлама жіберді"}</small><em>12.05.2024 · 10:{30 - index * 4}</em></div>{index < 2 && <b>•</b>}</div>)}</section> }
function Vehicle({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("more")}>‹</button><h1>Көлік туралы ақпарат</h1><button>✎</button></div><div className="vehicle-card"><small>Көлік</small><h2>GAZель Next</h2><p>777AAA02</p><div className="van">🚚</div><Info label="Жүк көтергіштік" value="1.5 т"/><Info label="Көлемі" value="12 м³"/><Info label="Жанармай түрі" value="Дизель"/><Info label="Келесі ТО" value="15.06.2024"/></div><button className="setting-row" onClick={() => go("documents")}>▣　Құжаттар <b>›</b></button><button className="setting-row">◉　Сақтандыру <b>›</b></button><button className="setting-row">⌖　Жөндеу тарихы <b>›</b></button></section> }
function Info({ label, value }: { label: string; value: string }) { return <div className="info-line"><span>{label}</span><b>{value}</b></div> }
function DispatcherProfile({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button onClick={() => go("more")}>⚙</button><h1>Профиль</h1><span/></div><div className="profile-card role-profile-card"><span className="role-avatar large">НӘ</span><h1>Нұрлан Әбілрахманов</h1><p>Экспедитор</p><strong>+7 777 123 45 67</strong><small>n.abdirakhmanov@qmart.kz</small></div>{["Жеке ақпарат", "Көлік туралы", "Параметрлер", "Тіл　　　　　　　 Қазақша", "Қолдау қызметі", "Қосымша туралы"].map((item, index) => <button className="setting-row role-setting" key={item} onClick={() => index === 1 ? go("vehicle") : index === 4 ? go("support") : undefined}>{item}<b>›</b></button>)}<button className="logout" onClick={() => go("dashboard")}>⇥　Шығу</button></section> }
function Fuel({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("more")}>‹</button><h1>Жанармай және шығындар</h1><span/></div><div className="role-tabs"><button className="active">Жанармай</button><button>Шығындар</button></div><div className="fuel-summary"><Info label="Бүгін" value="20 л　120 км　50 400 ₸"/><Info label="Апта бойынша" value="480 л　201 600 ₸"/></div><button className="role-primary">＋ Жанармай қосу</button><div className="role-section-title"><h3>Соңғы жазбалар</h3></div>{["12.05.2024, 08:20", "11.05.2024, 08:15", "10.05.2024, 10:00"].map((date, index) => <div className="fuel-row" key={date}><div><b>{date}</b><small>20 л · {index ? "KZ 777AAA02" : "Талғар"}</small></div><strong>{index === 1 ? "12 600 ₸" : "8 400 ₸"}</strong></div>)}</section> }
function Documents({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("more")}>‹</button><h1>Құжаттар</h1><span/></div>{["Жолсапарлар · 12 құжат", "Транспорт актілері · 8 құжат", "Қолма-қолсыз түсім · PDF · 2.4 MB", "Көлік куәлігі · PDF · 1.1 MB", "Техникалық байқау · PDF · 1.6 MB"].map((item, index) => <button className="setting-row role-setting" key={item}><span className={index > 1 ? "doc-icon red" : "doc-icon"}>▣</span>{item}<b>›</b></button>)}<button className="role-primary">Құжат қосу</button></section> }
function Support({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen support-screen"><div className="role-heading"><button className="back" onClick={() => go("more")}>‹</button><h1>Қолдау қызметі</h1><button>•••</button></div><div className="support-status">●　Онлайн</div><div className="chat-bubble incoming">Сәлеметсіз бе! Қалай көмектесе аламыз?</div><div className="chat-bubble outgoing">№100045 тапсырысы бойынша сұрақ бар</div><div className="chat-bubble incoming">Клиент мобильді қосымшаны өзгертуді сұрады</div><div className="support-input"><input placeholder="Хабарлама енгізіңіз..."/><button>➤</button></div></section> }
function DispatcherMore({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><h1>Көлік және баптаулар</h1><button className="setting-row role-setting" onClick={() => go("vehicle")}>▣　Көлік туралы ақпарат <b>›</b></button><button className="setting-row role-setting" onClick={() => go("fuel")}>♨　Жанармай және шығындар <b>›</b></button><button className="setting-row role-setting" onClick={() => go("documents")}>▤　Құжаттар <b>›</b></button><button className="setting-row role-setting" onClick={() => go("reports")}>▥　Есептер <b>›</b></button><button className="setting-row role-setting" onClick={() => go("support")}>♧　Қолдау қызметі <b>›</b></button></section> }
