"use client";

import { useState } from "react";

type Screen = "dashboard" | "products" | "product" | "receive" | "issue" | "stock" | "locations" | "inventory" | "orders" | "notifications" | "reports" | "profile" | "scanner" | "transfer" | "return" | "offline" | "more";
type Product = { name: string; sku: string; stock: number; price: number; state: "Қолжетімді" | "Аз қалды" | "Төмен"; icon: string };
const products: Product[] = [
  { name: "KRAUSZ Шам A60 12W E27 6500K", sku: "KLZ-A60-12W-6500", stock: 1250, price: 650, state: "Қолжетімді", icon: "◌" },
  { name: "KRAUSZ Проектор 100W 6500K IP65", sku: "KLZ-FL-100W-6500", stock: 320, price: 8500, state: "Аз қалды", icon: "▣" },
  { name: "KRAUSZ Панель LED 36W 595x595", sku: "KLZ-PL-36W-6500", stock: 560, price: 4200, state: "Қолжетімді", icon: "□" },
  { name: "KRAUSZ Линейный светильник 36W", sku: "KLZ-LN-36W-6500", stock: 150, price: 5200, state: "Төмен", icon: "▱" },
  { name: "KRAUSZ Розетка 2P+E 16A Белая", sku: "KLZ-SKT-2P-E-16A", stock: 890, price: 490, state: "Қолжетімді", icon: "⊙" },
];
const money = (value: number) => `${value.toLocaleString("kk-KZ")} ₸`;

export default function WarehouseApp() {
  const [screen, setScreen] = useState<Screen>("dashboard");
  const [logged, setLogged] = useState(false);
  const [selected, setSelected] = useState(products[0]);
  if (!logged) return <WarehouseLogin onLogin={() => setLogged(true)} />;
  const go = (next: Screen) => setScreen(next);
  return <main className="qmart-role warehouse-shell">
    <header className="role-header"><button onClick={() => go("more")}>☰</button><div><b>QMART</b><small>ҚОЙМА МЕНЕДЖЕРІ</small></div><button onClick={() => go("notifications")}>♧</button></header>
    {screen === "dashboard" && <WarehouseDashboard go={go} />}
    {screen === "products" && <WarehouseProducts go={go} onSelect={(product) => { setSelected(product); go("product"); }} />}
    {screen === "product" && <ProductDetail product={selected} go={go} />}
    {screen === "receive" && <WarehouseOperation type="receive" go={go} />}
    {screen === "issue" && <WarehouseOperation type="issue" go={go} />}
    {screen === "stock" && <WarehouseStock go={go} />}
    {screen === "locations" && <WarehouseLocations go={go} />}
    {screen === "inventory" && <Inventory go={go} />}
    {screen === "orders" && <WarehouseOrders go={go} />}
    {screen === "notifications" && <WarehouseNotifications go={go} />}
    {screen === "reports" && <WarehouseReports go={go} />}
    {screen === "profile" && <WarehouseProfile go={go} />}
    {screen === "scanner" && <WarehouseScanner go={go} />}
    {screen === "transfer" && <Transfer go={go} />}
    {screen === "return" && <ReturnGoods go={go} />}
    {screen === "offline" && <Offline go={go} />}
    {screen === "more" && <WarehouseMore go={go} />}
    <nav className="role-bottom"><button className={screen === "dashboard" ? "active" : ""} onClick={() => go("dashboard")}>⌂<small>Басты</small></button><button className={screen === "products" || screen === "product" || screen === "stock" ? "active" : ""} onClick={() => go("products")}>▤<small>Тауарлар</small></button><button className={screen === "receive" || screen === "issue" || screen === "transfer" || screen === "return" ? "active" : ""} onClick={() => go("receive")}>♧<small>Операциялар</small></button><button className={screen === "orders" ? "active" : ""} onClick={() => go("orders")}>▣<small>Тапсырыстар</small></button><button className={screen === "more" || screen === "profile" ? "active" : ""} onClick={() => go("more")}>•••<small>Көбірек</small></button></nav>
  </main>;
}

function WarehouseLogin({ onLogin }: { onLogin: () => void }) { return <main className="role-login warehouse-login"><div className="role-login-brand"><span>Q</span><b>QMART</b><small>ҚОЙМА МЕНЕДЖЕРІ</small></div><h1>Жүйеге кіру</h1><p>Аккаунтыңызға кіріп, қойма жұмысыңызды басқарыңыз</p><label>Телефон нөмірі<input placeholder="⌕ +7 (___) ___-__-__" inputMode="tel"/></label><label>Құпия сөз<input placeholder="••••••••••••" type="password"/></label><div className="login-check"><span>☑　Мені есте сақтау</span><a>Құпия сөзді ұмыттыңыз ба?</a></div><button className="role-primary" onClick={onLogin}>Кіру</button><div className="role-or">немесе</div><button className="role-secondary" onClick={onLogin}>▣　SMS арқылы кіру</button></main> }
function WarehouseDashboard({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-profile"><span className="role-avatar">НӘ</span><div><strong>Сәлеметсіз бе,<br/>Нұрлан!</strong><small>Қойма менеджері</small></div><button onClick={() => go("notifications")}>♧</button></div><section className="role-metrics warehouse-metrics"><small>Бүгінгі көрсеткіштер</small><p>12 мамыр, жексенбі</p><div><span>Кіріс<strong>120</strong><em>+12%</em></span><span>Қалдық<strong>3 456</strong><em>+2%</em></span><span>Шығыс<strong>98</strong><em>+8%</em></span><span>Тапсырыстар<strong>24</strong><em>+5%</em></span></div></section><div className="role-section-title"><h3>Жылдам әрекеттер</h3></div><div className="warehouse-actions"><button onClick={() => go("receive")}>▣<small>Тауарды қабылдау</small></button><button onClick={() => go("issue")}>▤<small>Тауарды шығару</small></button><button onClick={() => go("locations")}>▦<small>Қалдық санау</small></button><button onClick={() => go("transfer")}>♧<small>Трансфер</small></button><button onClick={() => go("return")}>↶<small>Қайтарым</small></button><button onClick={() => go("orders")}>▣<small>Жаңа тапсырыс</small></button></div><div className="role-section-title"><h3>Соңғы операциялар</h3><button onClick={() => go("reports")}>Барлығын көру ›</button></div><div className="operation-row"><span className="op green">▣</span><div><strong>Тауар қабылданды</strong><small>№P100045 · 11.05.2024 10:30</small></div><b className="positive">+250</b></div><div className="operation-row"><span className="op red">▤</span><div><strong>Тауар шығарылды</strong><small>№S010032 · 11.05.2024 15:20</small></div><b className="negative">−120</b></div><div className="operation-row"><span className="op gray">▦</span><div><strong>Қалдық санау</strong><small>№C100007 · 11.05.2024 18:10</small></div><b>✓</b></div></section> }
function WarehouseProducts({ go, onSelect }: { go: (screen: Screen) => void; onSelect: (product: Product) => void }) { const [query, setQuery] = useState(""); const filtered = products.filter((product) => `${product.name} ${product.sku}`.toLowerCase().includes(query.toLowerCase())); return <section className="role-screen"><div className="role-heading"><h1>Тауарлар</h1><button onClick={() => go("scanner")}>⌁</button></div><input className="role-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="⌕　Іздеу"/><div className="role-tabs"><button className="active">Барлығы 1256</button><button>Қалдықта</button><button>Аз қалған</button><button>Топтар</button></div>{filtered.map((product) => <button className="warehouse-product" key={product.sku} onClick={() => onSelect(product)}><span className="warehouse-product-icon">{product.icon}</span><div><strong>{product.name}</strong><small>SKU: {product.sku}</small><span>{product.stock} дана</span></div><em className={product.state === "Қолжетімді" ? "green" : product.state === "Аз қалды" ? "yellow" : "red"}>{product.state}</em></button>)}</section> }
function ProductDetail({ product, go }: { product: Product; go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("products")}>‹</button><h1>Тауар карточкасы</h1><button>✎</button></div><div className="product-detail-top"><span className="product-large-icon">{product.icon}</span><div><h2>{product.name}</h2><small>SKU: {product.sku}</small><em className="green">Қолжетімді</em></div></div><div className="role-tabs"><button className="active">Ақпараты</button><button>Қалдық</button><button>Операциялар</button><button>Суреттер</button></div><div className="detail-card"><Info label="Санат" value="Шамдар"/><Info label="Бренд" value="KRAUSZ"/><Info label="Штрихкод" value="4870123456789"/><Info label="Өлшем бірлік" value="дана"/><Info label="Сатып алу бағасы" value="450 ₸"/><Info label="Сату бағасы" value={money(product.price)}/><Info label="ҚҚС" value="12%"/><Info label="Ең аз қалдық" value="100 дана"/><Info label="Орналасуы" value="A-01-02-03"/></div><div className="operation-buttons"><button onClick={() => go("transfer")}>Трансфер</button><button onClick={() => go("issue")}>Операция⌄</button></div></section> }
function WarehouseOperation({ type, go }: { type: "receive" | "issue"; go: (screen: Screen) => void }) { const incoming = type === "receive"; return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("dashboard")}>‹</button><h1>{incoming ? "Қабылдау" : "Шығару"}</h1><button>⌁</button></div><div className="role-tabs"><button className="active">Жаңа {incoming ? "қабылдау" : "шығару"}</button><button>Тарих</button></div><div className="detail-card operation-form"><Info label="Құжат түрі" value={incoming ? "Кіріс құжаты (ПO)" : "Шығыс құжаты (СO)"}/><Info label={incoming ? "Жеткізуші" : "Алушы"} value={incoming ? "KRAUSZ Electric" : "Строймаг"}/><Info label="Құжат нөмірі" value={incoming ? "P010045" : "S010032"}/><Info label="Құжат күні" value="12.05.2024"/><Info label="Тауарлар" value={incoming ? "3 тауар · 250 дана" : "2 тауар · 120 дана"}/></div><div className="quantity-summary"><span>Тауарлар</span><b>{incoming ? "250 дана / 125 000 ₸" : "120 дана / 78 000 ₸"}</b></div><button className="role-primary" onClick={() => go("dashboard")}>{incoming ? "Тауарларды қосу" : "Тауарларды қосу"}</button><button className="role-primary secondary-green" onClick={() => go("dashboard")}>{incoming ? "Қабылдауды сақтау" : "Шығаруды сақтау"}</button></section> }
function WarehouseStock({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("products")}>‹</button><h1>Қалдықтар</h1><button>⌖</button></div><input className="role-input" placeholder="⌕　Іздеу"/><div className="stock-summary"><span><small>Барлық тауар</small><b>1 256</b></span><span><small>Жалпы қалдық</small><b>3 456</b></span><span><small>Құндылығы</small><b>2 450 800 ₸</b></span></div><div className="role-tabs"><button className="active">Барлығы</button><button>Аз қалған</button><button>Қозғалмай тұрған</button></div>{products.slice(0, 4).map((product) => <div className="warehouse-product stock-product" key={product.sku}><span className="warehouse-product-icon">{product.icon}</span><div><strong>{product.name}</strong><small>{product.stock} дана</small></div><b>{money(product.stock * product.price)}</b></div>)}</section> }
function WarehouseLocations({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("products")}>‹</button><h1>Склад картасы</h1><span/></div><input className="role-input" placeholder="⌕　Орналасуды іздеу"/><div className="role-tabs"><button className="active">Барлығы</button><button>A қоймасы</button><button>B қоймасы</button><button>C қоймасы</button></div><h3 className="warehouse-label">A қоймасы</h3><div className="location-grid">{["A-01-01","A-01-02","A-01-03","A-01-04","A-02-01","A-02-02","A-02-03","A-02-04","A-03-01","A-03-02","A-03-03","A-03-04"].map((item, index) => <button className={index === 1 || index === 7 ? "occupied" : ""} key={item}>{item}</button>)}</div><h3 className="warehouse-label">B қоймасы</h3><div className="location-grid">{["B-01-01","B-01-02","B-01-03","B-01-04","B-02-01","B-02-02","B-02-03","B-02-04"].map((item) => <button key={item}>{item}</button>)}</div></section> }
function Inventory({ go }: { go: (screen: Screen) => void }) { const [done, setDone] = useState(false); return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("stock")}>‹</button><h1>Қалдық санау</h1><button>⌁</button></div><div className="role-tabs"><button className="active">Жаңа санау</button><button>Тарих</button></div><div className="detail-card operation-form"><Info label="Санау түрі" value="Толық санау"/><Info label="Қойма" value="A қоймасы"/><Info label="Орындаушылар" value="Барлығы"/><Info label="Басталу күні" value="12.05.2024"/></div><div className="inventory-summary"><span>Тауарлар<b>1 256</b></span><span>Саналған<b>245</b></span><span>Сәйкестік<b>98%</b></span></div><button className="role-primary" onClick={() => setDone(true)}>{done ? "Санау басталды" : "Санауды бастау"}</button></section> }
function WarehouseOrders({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><h1>Тапсырыстар</h1><button>⌕</button></div><input className="role-input" placeholder="⌕　Іздеу"/><div className="role-tabs"><button className="active">Барлығы</button><button>Жаңа</button><button>Жинақталуда</button><button>Жөнелтілді</button></div>{["Строймаг","ЭлектроДом","Техносвет","1000 Мелочей"].map((name, index) => <button className="role-list-row" key={name} onClick={() => go("issue")}><span className="list-icon">♧</span><div><strong>S01003{index + 2} · {name}</strong><small>12.05.2024 · {index + 10}:30</small></div><div className="role-row-right"><b>{[78000,125000,92000,45000][index].toLocaleString("kk-KZ")} ₸</b><em className={`status ${index === 0 ? "blue" : index === 1 ? "yellow" : "green"}`}>{index === 0 ? "Жинақталуда" : index === 1 ? "Жаңа" : "Жөнелтілді"}</em></div></button>)}</section> }
function WarehouseNotifications({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><h1>Хабарламалар</h1><button>•••</button></div>{["Қалдық аз қалды", "Тауар қабылданды", "Санау аяқталды", "Тапсырыс дайын"].map((name, index) => <div className="notification-row" key={name}><span className={`notification-icon n${index}`}>●</span><div><strong>{name}</strong><small>{index === 0 ? "KRAUSZ Проектор 100W қоймада аз қалды" : "Операция сәтті сақталды"}</small><em>12.05.2024 · 10:30</em></div>{index < 2 && <b>•</b>}</div>)}<button className="role-primary" onClick={() => go("dashboard")}>Барлығын оқу</button></section> }
function WarehouseReports({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><h1>Есеп</h1><button>•••</button></div>{["Қалдық есебі", "Қозғалыс есебі", "Тауарлардың қозғалысы", "Қабылдау есебі", "Шығару есебі", "Қалдық бойынша ABC талдау", "Қоймадағы тұрған тауарлар"].map((name) => <button className="setting-row role-setting" key={name} onClick={() => go("stock")}>▣　{name}<b>›</b></button>)}</section> }
function WarehouseProfile({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button onClick={() => go("more")}>⚙</button><h1>Профиль</h1><span/></div><div className="profile-card role-profile-card"><span className="role-avatar large">НӘ</span><h1>Нұрлан Әбілрахманов</h1><p>Қойма менеджері</p><strong>n.abdirakhmanov@qmart.kz</strong></div>{["Профильді өңдеу", "Қоймалар", "Пайдаланушылар", "Құрылғы баптаулары", "Тіл　　　　　　　 Қазақша", "Қолдау қызметі"].map((item, index) => <button className="setting-row role-setting" key={item} onClick={() => index === 5 ? go("notifications") : undefined}>{item}<b>›</b></button>)}<button className="logout" onClick={() => go("dashboard")}>⇥　Шығу</button></section> }
function WarehouseScanner({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen scanner-screen"><div className="role-heading"><button className="back" onClick={() => go("products")}>‹</button><h1>Штрихкод сканері</h1><button>⌁</button></div><div className="scanner-box"><div className="scan-corners">▣</div><p>Штрихкодты рамкаға орналастырыңыз</p></div><div className="role-tabs"><button>Тарих</button><button className="active">Қолмен енгізу</button></div><input className="role-input" placeholder="Штрихкод енгізу　⌕"/><div className="scanner-actions"><button>♨<small>Фонарик</small></button><button>▧<small>Галерея</small></button></div><button className="role-primary" onClick={() => go("product")}>Тауарды ашу</button></section> }
function Transfer({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("more")}>‹</button><h1>Трансфер</h1><button>▣</button></div><div className="role-tabs"><button className="active">Жаңа трансфер</button><button>Тарих</button></div><div className="detail-card operation-form"><Info label="Көлік" value="A-01-02-03　›"/><Info label="Қойма" value="A-02-04-01　›"/><Info label="Тауар" value={products[0].name}/><Info label="Саны" value="100 дана"/></div><button className="role-primary" onClick={() => go("products")}>Трансферді сақтау</button></section> }
function ReturnGoods({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("more")}>‹</button><h1>Қайтарым (Return)</h1><button>▣</button></div><div className="role-tabs"><button className="active">Жаңа қайтарым</button><button>Тарих</button></div><div className="detail-card operation-form"><Info label="Құжат түрі" value="Қайтарым (RTN)"/><Info label="Алушы" value="Строймаг"/><Info label="Құжат нөмірі" value="RTN10005"/><Info label="Құжат күні" value="12.05.2024"/><Info label="Тауарлар" value="1 тауар · 10 дана"/></div><button className="role-primary" onClick={() => go("products")}>Қайтарымды сақтау</button></section> }
function Offline({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen offline-screen"><span className="offline-symbol">⌁</span><h1>Интернет байланысы жоқ</h1><p>Кейбір функциялар істемейді. Деректер байланыс қалпына келгенде синхрондалады.</p><button className="role-primary" onClick={() => go("dashboard")}>Қайта қосылу</button></section> }
function WarehouseMore({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><h1>Көбірек</h1><button className="setting-row role-setting" onClick={() => go("profile")}>⚙　Профиль және баптаулар <b>›</b></button><button className="setting-row role-setting" onClick={() => go("reports")}>▥　Есеп <b>›</b></button><button className="setting-row role-setting" onClick={() => go("scanner")}>⌁　Штрихкод сканері <b>›</b></button><button className="setting-row role-setting" onClick={() => go("offline")}>⌁　Offline режимі <b>›</b></button><button className="setting-row role-setting" onClick={() => go("notifications")}>♧　Хабарламалар <b>›</b></button></section> }
function Info({ label, value }: { label: string; value: string }) { return <div className="info-line"><span>{label}</span><b>{value}</b></div> }
