"use client";

import { useEffect, useMemo, useState } from "react";

type Screen = "dashboard" | "products" | "product" | "receive" | "issue" | "stock" | "locations" | "inventory" | "orders" | "order" | "notifications" | "reports" | "profile" | "scanner" | "transfer" | "return" | "offline" | "more";
type Product = { name: string; sku: string; stock: number; price: number; state: "Қолжетімді" | "Аз қалды" | "Төмен"; icon: string };
type OrderStatus = "new" | "picking" | "ready" | "labeled" | "shipped";
type WarehouseOrder = { id: string; store: string; address: string; total: number; createdAt: string; status: OrderStatus; items: { name: string; quantity: number; price: number }[]; sticker?: string; waybill?: string };
const products: Product[] = [
  { name: "KRAUSZ Шам A60 12W E27 6500K", sku: "KLZ-A60-12W-6500", stock: 1250, price: 650, state: "Қолжетімді", icon: "◌" },
  { name: "KRAUSZ Проектор 100W 6500K IP65", sku: "KLZ-FL-100W-6500", stock: 320, price: 8500, state: "Аз қалды", icon: "▣" },
  { name: "KRAUSZ Панель LED 36W 595x595", sku: "KLZ-PL-36W-6500", stock: 560, price: 4200, state: "Қолжетімді", icon: "□" },
  { name: "KRAUSZ Линейный светильник 36W", sku: "KLZ-LN-36W-6500", stock: 150, price: 5200, state: "Төмен", icon: "▱" },
  { name: "KRAUSZ Розетка 2P+E 16A Белая", sku: "KLZ-SKT-2P-E-16A", stock: 890, price: 490, state: "Қолжетімді", icon: "⊙" },
];
const money = (value: number) => `${value.toLocaleString("kk-KZ")} ₸`;
const statusLabel: Record<OrderStatus, string> = { new: "Қоймаға түсті", picking: "Жинауда", ready: "Дайын", labeled: "Құжаттары бекітілді", shipped: "Жөнелтілді" };
const orderStatusClass: Record<OrderStatus, string> = { new: "blue", picking: "yellow", ready: "green", labeled: "green", shipped: "green" };
const initialOrders: WarehouseOrder[] = [
  { id: "№100045", store: "Строймаг", address: "Алматы қ., Райымбек 348", total: 245000, createdAt: "12.05.2024 · 10:30", status: "new", items: [{ name: products[0].name, quantity: 10, price: 650 }, { name: products[1].name, quantity: 2, price: 8500 }, { name: products[2].name, quantity: 5, price: 4200 }] },
  { id: "№100046", store: "ЭлектроДом", address: "Алматы қ., Төле би 215", total: 185000, createdAt: "12.05.2024 · 11:15", status: "picking", items: [{ name: products[0].name, quantity: 20, price: 650 }, { name: products[4].name, quantity: 12, price: 490 }] },
  { id: "№100047", store: "Техносвет", address: "Алматы қ., Абай 68", total: 92000, createdAt: "12.05.2024 · 12:00", status: "ready", items: [{ name: products[2].name, quantity: 8, price: 4200 }] },
  { id: "№100048", store: "Светлый дом", address: "Алматы қ., Сайын 22", total: 70000, createdAt: "12.05.2024 · 13:00", status: "labeled", sticker: "ST-100048", waybill: "НК-100048", items: [{ name: products[3].name, quantity: 5, price: 5200 }] },
];

export default function WarehouseApp() {
  const [screen, setScreen] = useState<Screen>("dashboard");
  const [logged, setLogged] = useState(false);
  const [selected, setSelected] = useState(products[0]);
  const [orders, setOrders] = useState<WarehouseOrder[]>(initialOrders);
  const [selectedOrderId, setSelectedOrderId] = useState<string>(initialOrders[0].id);
  const selectedOrder = useMemo(() => orders.find((order) => order.id === selectedOrderId) ?? orders[0], [orders, selectedOrderId]);
  useEffect(() => {
    const saved = localStorage.getItem("alsat-warehouse-orders");
    if (saved) { try { setOrders(JSON.parse(saved)); } catch { localStorage.removeItem("alsat-warehouse-orders"); } }
    const agentOrders = localStorage.getItem("alsat-agent-orders");
    if (agentOrders) {
      try {
        const incoming = JSON.parse(agentOrders) as Array<{ id: string; client: string; total: number; createdAt: string; items: Array<{ name: string; price: number }> }>;
        setOrders((current) => {
          const additions = incoming.filter((item) => !current.some((order) => order.id === item.id)).map((item) => ({ id: item.id, store: item.client, address: "Мекенжайы тапсырыстан алынады", total: item.total, createdAt: item.createdAt, status: "new" as OrderStatus, items: item.items.map((line) => ({ name: line.name, quantity: 1, price: line.price })) }));
          const next = [...additions, ...current];
          localStorage.setItem("alsat-warehouse-orders", JSON.stringify(next));
          return next;
        });
      } catch { /* Ignore an incomplete offline order payload. */ }
    }
  }, []);
  useEffect(() => { if (logged) localStorage.setItem("alsat-warehouse-orders", JSON.stringify(orders)); }, [orders, logged]);
  if (!logged) return <WarehouseLogin onLogin={() => setLogged(true)} />;
  const go = (next: Screen) => setScreen(next);
  const openOrder = (order: WarehouseOrder) => { setSelectedOrderId(order.id); go("order"); };
  const updateOrder = (patch: Partial<WarehouseOrder>) => { if (!selectedOrder) return; setOrders((current) => current.map((order) => order.id === selectedOrder.id ? { ...order, ...patch } : order)); };
  return <main className="qmart-role warehouse-shell">
    <header className="role-header"><button onClick={() => go("more")}>☰</button><div><b>QMART</b><small>ҚОЙМА МЕНЕДЖЕРІ</small></div><button onClick={() => go("notifications")}>♧</button></header>
    {screen === "dashboard" && <WarehouseDashboard go={go} />}
    {screen === "products" && <WarehouseProducts go={go} onSelect={(product) => { setSelected(product); go("product"); }} />}
    {screen === "product" && <ProductDetail product={selected} go={go} />}
    {screen === "receive" && <WarehouseOperation type="receive" go={go} />}
    {screen === "issue" && <WarehouseOperation type="issue" go={go} />}
    {screen === "stock" && <WarehouseStock go={go} />}
    {screen === "locations" && <WarehouseLocations go={go} />}
    {screen === "inventory" && <Inventory go={go} />}
    {screen === "orders" && <WarehouseOrders orders={orders} go={go} onSelect={openOrder} />}
    {screen === "order" && selectedOrder && <WarehouseOrderDetail order={selectedOrder} go={go} updateOrder={updateOrder} />}
    {screen === "notifications" && <WarehouseNotifications go={go} />}
    {screen === "reports" && <WarehouseReports go={go} />}
    {screen === "profile" && <WarehouseProfile go={go} />}
    {screen === "scanner" && <WarehouseScanner go={go} />}
    {screen === "transfer" && <Transfer go={go} />}
    {screen === "return" && <ReturnGoods go={go} />}
    {screen === "offline" && <Offline go={go} />}
    {screen === "more" && <WarehouseMore go={go} />}
    <nav className="role-bottom"><button className={screen === "dashboard" ? "active" : ""} onClick={() => go("dashboard")}>⌂<small>Басты</small></button><button className={screen === "products" || screen === "product" || screen === "stock" ? "active" : ""} onClick={() => go("products")}>▤<small>Тауарлар</small></button><button className={screen === "receive" || screen === "issue" || screen === "transfer" || screen === "return" ? "active" : ""} onClick={() => go("receive")}>♧<small>Операциялар</small></button><button className={screen === "orders" ? "active" : ""} onClick={() => go("orders")}>▣<small>Тапсырыстар</small></button><button className={screen === "more" || screen === "profile" ? "active" : ""} onClick={() => go("more")}>•••<small>Көбірек</small></button></nav>
  </main>;
}

function WarehouseLogin({ onLogin }: { onLogin: () => void }) { return <main className="role-login warehouse-login"><div className="role-login-brand"><span>Q</span><b>QMART</b><small>ҚОЙМА МЕНЕДЖЕРІ</small></div><h1>Жүйеге кіру</h1><p>Аккаунтыңызға кіріп, қойма жұмысыңызды басқарыңыз</p><label>Телефон нөмірі<input placeholder="⌕ +7 (___) ___-__-__" inputMode="tel"/></label><label>Құпия сөз<input placeholder="••••••••••••" type="password"/></label><div className="login-check"><span>☑　Мені есте сақтау</span><a>Құпия сөзді ұмыттыңыз ба?</a></div><button className="role-primary" onClick={onLogin}>Кіру</button><div className="role-or">немесе</div><button className="role-secondary" onClick={onLogin}>▣　SMS арқылы кіру</button></main> }
function WarehouseDashboard({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-profile"><span className="role-avatar">НӘ</span><div><strong>Сәлеметсіз бе,<br/>Нұрлан!</strong><small>Қойма менеджері</small></div><button onClick={() => go("notifications")}>♧</button></div><section className="role-metrics warehouse-metrics"><small>Бүгінгі көрсеткіштер</small><p>12 мамыр, жексенбі</p><div><span>Кіріс<strong>120</strong><em>+12%</em></span><span>Қалдық<strong>3 456</strong><em>+2%</em></span><span>Шығыс<strong>98</strong><em>+8%</em></span><span>Тапсырыстар<strong>24</strong><em>+5%</em></span></div></section><div className="role-section-title"><h3>Жылдам әрекеттер</h3></div><div className="warehouse-actions"><button onClick={() => go("receive")}>▣<small>Тауарды қабылдау</small></button><button onClick={() => go("issue")}>▤<small>Тауарды шығару</small></button><button onClick={() => go("locations")}>▦<small>Қалдық санау</small></button><button onClick={() => go("transfer")}>♧<small>Трансфер</small></button><button onClick={() => go("return")}>↶<small>Қайтарым</small></button><button onClick={() => go("orders")}>▣<small>Жаңа тапсырыс</small></button></div><div className="role-section-title"><h3>Соңғы операциялар</h3><button onClick={() => go("reports")}>Барлығын көру ›</button></div><div className="operation-row"><span className="op green">▣</span><div><strong>Тауар қабылданды</strong><small>№P100045 · 11.05.2024 10:30</small></div><b className="positive">+250</b></div><div className="operation-row"><span className="op red">▤</span><div><strong>Тауар шығарылды</strong><small>№S010032 · 11.05.2024 15:20</small></div><b className="negative">−120</b></div><div className="operation-row"><span className="op gray">▦</span><div><strong>Қалдық санау</strong><small>№C100007 · 11.05.2024 18:10</small></div><b>✓</b></div></section> }
function WarehouseProducts({ go, onSelect }: { go: (screen: Screen) => void; onSelect: (product: Product) => void }) { const [query, setQuery] = useState(""); const filtered = products.filter((product) => `${product.name} ${product.sku}`.toLowerCase().includes(query.toLowerCase())); return <section className="role-screen"><div className="role-heading"><h1>Тауарлар</h1><button onClick={() => go("scanner")}>⌁</button></div><input className="role-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="⌕　Іздеу"/><div className="role-tabs"><button className="active">Барлығы 1256</button><button>Қалдықта</button><button>Аз қалған</button><button>Топтар</button></div>{filtered.map((product) => <button className="warehouse-product" key={product.sku} onClick={() => onSelect(product)}><span className="warehouse-product-icon">{product.icon}</span><div><strong>{product.name}</strong><small>SKU: {product.sku}</small><span>{product.stock} дана</span></div><em className={product.state === "Қолжетімді" ? "green" : product.state === "Аз қалды" ? "yellow" : "red"}>{product.state}</em></button>)}</section> }
function ProductDetail({ product, go }: { product: Product; go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("products")}>‹</button><h1>Тауар карточкасы</h1><button>✎</button></div><div className="product-detail-top"><span className="product-large-icon">{product.icon}</span><div><h2>{product.name}</h2><small>SKU: {product.sku}</small><em className="green">Қолжетімді</em></div></div><div className="role-tabs"><button className="active">Ақпараты</button><button>Қалдық</button><button>Операциялар</button><button>Суреттер</button></div><div className="detail-card"><Info label="Санат" value="Шамдар"/><Info label="Бренд" value="KRAUSZ"/><Info label="Штрихкод" value="4870123456789"/><Info label="Өлшем бірлік" value="дана"/><Info label="Сатып алу бағасы" value="450 ₸"/><Info label="Сату бағасы" value={money(product.price)}/><Info label="ҚҚС" value="12%"/><Info label="Ең аз қалдық" value="100 дана"/><Info label="Орналасуы" value="A-01-02-03"/></div><div className="operation-buttons"><button onClick={() => go("transfer")}>Трансфер</button><button onClick={() => go("issue")}>Операция⌄</button></div></section> }
function WarehouseOperation({ type, go }: { type: "receive" | "issue"; go: (screen: Screen) => void }) { const incoming = type === "receive"; return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("dashboard")}>‹</button><h1>{incoming ? "Қабылдау" : "Шығару"}</h1><button>⌁</button></div><div className="role-tabs"><button className="active">Жаңа {incoming ? "қабылдау" : "шығару"}</button><button>Тарих</button></div><div className="detail-card operation-form"><Info label="Құжат түрі" value={incoming ? "Кіріс құжаты (ПO)" : "Шығыс құжаты (СO)"}/><Info label={incoming ? "Жеткізуші" : "Алушы"} value={incoming ? "KRAUSZ Electric" : "Строймаг"}/><Info label="Құжат нөмірі" value={incoming ? "P010045" : "S010032"}/><Info label="Құжат күні" value="12.05.2024"/><Info label="Тауарлар" value={incoming ? "3 тауар · 250 дана" : "2 тауар · 120 дана"}/></div><div className="quantity-summary"><span>Тауарлар</span><b>{incoming ? "250 дана / 125 000 ₸" : "120 дана / 78 000 ₸"}</b></div><button className="role-primary" onClick={() => go("dashboard")}>{incoming ? "Тауарларды қосу" : "Тауарларды қосу"}</button><button className="role-primary secondary-green" onClick={() => go("dashboard")}>{incoming ? "Қабылдауды сақтау" : "Шығаруды сақтау"}</button></section> }
function WarehouseStock({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("products")}>‹</button><h1>Қалдықтар</h1><button>⌖</button></div><input className="role-input" placeholder="⌕　Іздеу"/><div className="stock-summary"><span><small>Барлық тауар</small><b>1 256</b></span><span><small>Жалпы қалдық</small><b>3 456</b></span><span><small>Құндылығы</small><b>2 450 800 ₸</b></span></div><div className="role-tabs"><button className="active">Барлығы</button><button>Аз қалған</button><button>Қозғалмай тұрған</button></div>{products.slice(0, 4).map((product) => <div className="warehouse-product stock-product" key={product.sku}><span className="warehouse-product-icon">{product.icon}</span><div><strong>{product.name}</strong><small>{product.stock} дана</small></div><b>{money(product.stock * product.price)}</b></div>)}</section> }
function WarehouseLocations({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("products")}>‹</button><h1>Склад картасы</h1><span/></div><input className="role-input" placeholder="⌕　Орналасуды іздеу"/><div className="role-tabs"><button className="active">Барлығы</button><button>A қоймасы</button><button>B қоймасы</button><button>C қоймасы</button></div><h3 className="warehouse-label">A қоймасы</h3><div className="location-grid">{["A-01-01","A-01-02","A-01-03","A-01-04","A-02-01","A-02-02","A-02-03","A-02-04","A-03-01","A-03-02","A-03-03","A-03-04"].map((item, index) => <button className={index === 1 || index === 7 ? "occupied" : ""} key={item}>{item}</button>)}</div><h3 className="warehouse-label">B қоймасы</h3><div className="location-grid">{["B-01-01","B-01-02","B-01-03","B-01-04","B-02-01","B-02-02","B-02-03","B-02-04"].map((item) => <button key={item}>{item}</button>)}</div></section> }
function Inventory({ go }: { go: (screen: Screen) => void }) { const [done, setDone] = useState(false); return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("stock")}>‹</button><h1>Қалдық санау</h1><button>⌁</button></div><div className="role-tabs"><button className="active">Жаңа санау</button><button>Тарих</button></div><div className="detail-card operation-form"><Info label="Санау түрі" value="Толық санау"/><Info label="Қойма" value="A қоймасы"/><Info label="Орындаушылар" value="Барлығы"/><Info label="Басталу күні" value="12.05.2024"/></div><div className="inventory-summary"><span>Тауарлар<b>1 256</b></span><span>Саналған<b>245</b></span><span>Сәйкестік<b>98%</b></span></div><button className="role-primary" onClick={() => setDone(true)}>{done ? "Санау басталды" : "Санауды бастау"}</button></section> }
function WarehouseOrders({ orders, go, onSelect }: { orders: WarehouseOrder[]; go: (screen: Screen) => void; onSelect: (order: WarehouseOrder) => void }) {
  const [filter, setFilter] = useState<OrderStatus | "all">("all");
  const visible = filter === "all" ? orders : orders.filter((order) => order.status === filter);
  return <section className="role-screen"><div className="role-heading"><h1>Тапсырыстар</h1><button onClick={() => go("scanner")}>⌕</button></div><p className="role-muted">СӨ өкілдерінен түскен тапсырыстарды қабылдап, жинауды басқарыңыз.</p><div className="role-tabs"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>Барлығы {orders.length}</button><button className={filter === "new" ? "active" : ""} onClick={() => setFilter("new")}>Қоймаға түсті</button><button className={filter === "picking" ? "active" : ""} onClick={() => setFilter("picking")}>Жинауда</button><button className={filter === "ready" ? "active" : ""} onClick={() => setFilter("ready")}>Дайын</button></div>{visible.length ? visible.map((order) => <button className="role-list-row" key={order.id} onClick={() => onSelect(order)}><span className="list-icon">♧</span><div><strong>{order.id} · {order.store}</strong><small>{order.address}<br/>{order.createdAt} · {order.items.length} позиция</small></div><div className="role-row-right"><b>{money(order.total)}</b><em className={`status ${orderStatusClass[order.status]}`}>{statusLabel[order.status]}</em></div></button>) : <div className="empty">Бұл сүзгіде тапсырыс жоқ</div>}</section>
}

function WarehouseOrderDetail({ order, go, updateOrder }: { order: WarehouseOrder; go: (screen: Screen) => void; updateOrder: (patch: Partial<WarehouseOrder>) => void }) {
  const [sticker, setSticker] = useState(order.sticker ?? "");
  const [waybill, setWaybill] = useState(order.waybill ?? "");
  const steps: Array<{ key: OrderStatus; label: string }> = [{ key: "new", label: "Қоймаға түсті" }, { key: "picking", label: "Жинауға кірістім" }, { key: "ready", label: "Жинау аяқталды" }, { key: "labeled", label: "Стикер және накладной" }, { key: "shipped", label: "Жөнелтілді" }];
  const currentIndex = steps.findIndex((step) => step.key === order.status);
  const advance = () => {
    if (order.status === "new") updateOrder({ status: "picking" });
    else if (order.status === "picking") updateOrder({ status: "ready" });
    else if (order.status === "ready" && sticker.trim() && waybill.trim()) updateOrder({ status: "labeled", sticker: sticker.trim(), waybill: waybill.trim() });
    else if (order.status === "labeled") updateOrder({ status: "shipped" });
  };
  const actionLabel = order.status === "new" ? "Қабылдадым, жинауға кірістім" : order.status === "picking" ? "Жинау аяқталды — дайын" : order.status === "ready" ? "Стикер және накладной бекіту" : order.status === "labeled" ? "Жөнелтуге беру" : "Тапсырыс аяқталды";
  return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("orders")}>‹</button><h1>{order.id}</h1><button>⌯</button></div><div className="order-detail-head"><div><span className={`status ${orderStatusClass[order.status]}`}>{statusLabel[order.status]}</span><h2>{order.store}</h2><small>{order.address}</small></div><b>{money(order.total)}</b></div><div className="workflow">{steps.map((step, index) => <div className={`workflow-step ${index < currentIndex ? "done" : ""} ${index === currentIndex ? "active" : ""}`} key={step.key}><span>{index < currentIndex ? "✓" : index + 1}</span><div><strong>{step.label}</strong><small>{index === 0 ? "СӨ тапсырысы автоматты түсті" : index === 1 ? "Қоймашы жинауды бастайды" : index === 2 ? "Барлық позиция жиналды" : index === 3 ? "Стикер және накладной қосылады" : "Экспедиторға берілді"}</small></div></div>)}</div><div className="role-section-title"><h3>Тауарлар ({order.items.length})</h3><button onClick={() => go("products")}>Қоймадан көру</button></div><div className="detail-card product-lines">{order.items.map((item) => <span key={item.name}>{item.name}<b>{item.quantity} × {money(item.price)}</b></span>)}<strong>Жалпы сома <b>{money(order.total)}</b></strong></div>{order.status === "ready" && <div className="document-card"><h3>Жөнелтуге дайындау</h3><p>Жиналған қораптың сыртына стикер жапсырып, накладнойды үстіне қойыңыз.</p><label>Стикер нөмірі<input value={sticker} onChange={(event) => setSticker(event.target.value)} placeholder="Мысалы: ST-100047" /></label><label>Накладной нөмірі<input value={waybill} onChange={(event) => setWaybill(event.target.value)} placeholder="Мысалы: НК-100047" /></label><div className="document-checks"><span>☐ Стикер жапсырылды</span><span>☐ Накладной қойылды</span></div></div>}{order.status === "labeled" && <div className="document-card success-card"><strong>✓ Құжаттар дайын</strong><span>Стикер: {order.sticker}</span><span>Накладной: {order.waybill}</span></div>}<button className="role-primary" onClick={advance} disabled={order.status === "shipped" || (order.status === "ready" && (!sticker.trim() || !waybill.trim()))}>{actionLabel}</button>{order.status === "ready" && (!sticker.trim() || !waybill.trim()) && <small className="form-hint">Алдымен стикер және накладной нөмірін енгізіңіз.</small>}</section>
}
function WarehouseNotifications({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><h1>Хабарламалар</h1><button>•••</button></div>{["Қалдық аз қалды", "Тауар қабылданды", "Санау аяқталды", "Тапсырыс дайын"].map((name, index) => <div className="notification-row" key={name}><span className={`notification-icon n${index}`}>●</span><div><strong>{name}</strong><small>{index === 0 ? "KRAUSZ Проектор 100W қоймада аз қалды" : "Операция сәтті сақталды"}</small><em>12.05.2024 · 10:30</em></div>{index < 2 && <b>•</b>}</div>)}<button className="role-primary" onClick={() => go("dashboard")}>Барлығын оқу</button></section> }
function WarehouseReports({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><h1>Есеп</h1><button>•••</button></div>{["Қалдық есебі", "Қозғалыс есебі", "Тауарлардың қозғалысы", "Қабылдау есебі", "Шығару есебі", "Қалдық бойынша ABC талдау", "Қоймадағы тұрған тауарлар"].map((name) => <button className="setting-row role-setting" key={name} onClick={() => go("stock")}>▣　{name}<b>›</b></button>)}</section> }
function WarehouseProfile({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button onClick={() => go("more")}>⚙</button><h1>Профиль</h1><span/></div><div className="profile-card role-profile-card"><span className="role-avatar large">НӘ</span><h1>Нұрлан Әбілрахманов</h1><p>Қойма менеджері</p><strong>n.abdirakhmanov@qmart.kz</strong></div>{["Профильді өңдеу", "Қоймалар", "Пайдаланушылар", "Құрылғы баптаулары", "Тіл　　　　　　　 Қазақша", "Қолдау қызметі"].map((item, index) => <button className="setting-row role-setting" key={item} onClick={() => index === 5 ? go("notifications") : undefined}>{item}<b>›</b></button>)}<button className="logout" onClick={() => go("dashboard")}>⇥　Шығу</button></section> }
function WarehouseScanner({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen scanner-screen"><div className="role-heading"><button className="back" onClick={() => go("products")}>‹</button><h1>Штрихкод сканері</h1><button>⌁</button></div><div className="scanner-box"><div className="scan-corners">▣</div><p>Штрихкодты рамкаға орналастырыңыз</p></div><div className="role-tabs"><button>Тарих</button><button className="active">Қолмен енгізу</button></div><input className="role-input" placeholder="Штрихкод енгізу　⌕"/><div className="scanner-actions"><button>♨<small>Фонарик</small></button><button>▧<small>Галерея</small></button></div><button className="role-primary" onClick={() => go("product")}>Тауарды ашу</button></section> }
function Transfer({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("more")}>‹</button><h1>Трансфер</h1><button>▣</button></div><div className="role-tabs"><button className="active">Жаңа трансфер</button><button>Тарих</button></div><div className="detail-card operation-form"><Info label="Көлік" value="A-01-02-03　›"/><Info label="Қойма" value="A-02-04-01　›"/><Info label="Тауар" value={products[0].name}/><Info label="Саны" value="100 дана"/></div><button className="role-primary" onClick={() => go("products")}>Трансферді сақтау</button></section> }
function ReturnGoods({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><div className="role-heading"><button className="back" onClick={() => go("more")}>‹</button><h1>Қайтарым (Return)</h1><button>▣</button></div><div className="role-tabs"><button className="active">Жаңа қайтарым</button><button>Тарих</button></div><div className="detail-card operation-form"><Info label="Құжат түрі" value="Қайтарым (RTN)"/><Info label="Алушы" value="Строймаг"/><Info label="Құжат нөмірі" value="RTN10005"/><Info label="Құжат күні" value="12.05.2024"/><Info label="Тауарлар" value="1 тауар · 10 дана"/></div><button className="role-primary" onClick={() => go("products")}>Қайтарымды сақтау</button></section> }
function Offline({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen offline-screen"><span className="offline-symbol">⌁</span><h1>Интернет байланысы жоқ</h1><p>Кейбір функциялар істемейді. Деректер байланыс қалпына келгенде синхрондалады.</p><button className="role-primary" onClick={() => go("dashboard")}>Қайта қосылу</button></section> }
function WarehouseMore({ go }: { go: (screen: Screen) => void }) { return <section className="role-screen"><h1>Көбірек</h1><button className="setting-row role-setting" onClick={() => go("profile")}>⚙　Профиль және баптаулар <b>›</b></button><button className="setting-row role-setting" onClick={() => go("reports")}>▥　Есеп <b>›</b></button><button className="setting-row role-setting" onClick={() => go("scanner")}>⌁　Штрихкод сканері <b>›</b></button><button className="setting-row role-setting" onClick={() => go("offline")}>⌁　Offline режимі <b>›</b></button><button className="setting-row role-setting" onClick={() => go("notifications")}>♧　Хабарламалар <b>›</b></button></section> }
function Info({ label, value }: { label: string; value: string }) { return <div className="info-line"><span>{label}</span><b>{value}</b></div> }
