"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { isSupabaseConfigured } from "../lib/supabase";
import { supabase } from "../lib/supabase";
import { roleLabel } from "../lib/workspace-auth";

type Product = { id: number; name: string; sku: string; price: number; stock: number; commission: number; workspace: boolean; agents: boolean; marketplace: boolean };
const money = new Intl.NumberFormat("kk-KZ", { style: "currency", currency: "KZT", maximumFractionDigits: 0 });
const starter: Product[] = [{ id: 1, name: "Кабель ВВГнг 3×2.5", sku: "VVG-325", price: 78500, stock: 36, commission: 5, workspace: true, agents: true, marketplace: false }, { id: 2, name: "Автоматты ажыратқыш C16", sku: "AB-C16", price: 2450, stock: 120, commission: 7, workspace: true, agents: true, marketplace: true }];
const nav = [{ id: "home", icon: "⌂", label: "Басты бет" }, { id: "products", icon: "▦", label: "Тауарлар" }, { id: "agents", icon: "◉", label: "Сауда өкілдері" }, { id: "orders", icon: "▤", label: "Тапсырыстар" }, { id: "commissions", icon: "₸", label: "Комиссиялар" }];

export default function Home() {
  const [screen, setScreen] = useState("home"), [registered, setRegistered] = useState(false), [products, setProducts] = useState<Product[]>(starter), [notice, setNotice] = useState(""), [companyId, setCompanyId] = useState<string | null>(null);
  useEffect(() => { const forceRegistration = new URLSearchParams(window.location.search).get("start") === "registration"; setRegistered(forceRegistration ? false : localStorage.getItem("alsat-company") === "1"); setCompanyId(localStorage.getItem("alsat-company-id")); const saved = localStorage.getItem("alsat-products"); if (saved) setProducts(JSON.parse(saved)); }, []);
  useEffect(() => { if (!supabase || !companyId) return; supabase.from("products").select("id,name,sku,price,stock,commission_rate,workspace_active,agent_visible,marketplace_published").eq("company_id", companyId).order("created_at", { ascending: false }).then(({ data }) => { if (data?.length) setProducts(data.map(p => ({ id: p.id, name: p.name, sku: p.sku ?? "", price: Number(p.price), stock: p.stock, commission: Number(p.commission_rate), workspace: p.workspace_active, agents: p.agent_visible, marketplace: p.marketplace_published }))); }); }, [companyId]);
  useEffect(() => { if (registered) localStorage.setItem("alsat-products", JSON.stringify(products)); }, [products, registered]);
  const agentProducts = products.filter(p => p.workspace && p.agents);
  const totalStock = products.reduce((n, p) => n + p.stock, 0);
  async function saveCompany(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); let id: string | null = null; let ownerId: string | null = null; if (supabase) { const { data: userData } = await supabase.auth.getUser(); ownerId = userData.user?.id ?? null; const { data: row } = await supabase.from("companies").insert({ ...(ownerId ? { owner_id: ownerId } : {}), name: String(data.get("company")), bin: String(data.get("bin") || ""), city: String(data.get("city")), phone: String(data.get("phone")) }).select("id").single(); id = row?.id ?? null; if (id && ownerId) await supabase.from("company_members").upsert({ company_id: id, user_id: ownerId, role: "owner", full_name: String(data.get("company")), status: "active" }); } if (id) { localStorage.setItem("alsat-company-id", id); setCompanyId(id); } localStorage.setItem("alsat-company", "1"); setRegistered(true); setNotice(id ? `Компания Supabase-ке сақталды · ${roleLabel("owner")}` : "Demo workspace ашылды. Көппайдаланушы режимі үшін Auth арқылы кіріңіз."); }
  async function addProduct(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const product: Product = { id: Date.now(), name: String(data.get("name")), sku: String(data.get("sku")), price: Number(data.get("price")), stock: Number(data.get("stock")), commission: Number(data.get("commission")), workspace: data.get("workspace") === "on", agents: data.get("agents") === "on", marketplace: data.get("marketplace") === "on" }; if (supabase && companyId) await supabase.from("products").insert({ company_id: companyId, name: product.name, sku: product.sku, price: product.price, stock: product.stock, commission_rate: product.commission, workspace_active: product.workspace, agent_visible: product.agents, marketplace_published: product.marketplace }); setProducts([product, ...products]); event.currentTarget.reset(); setScreen("products"); setNotice(supabase && companyId ? "Тауар Supabase-ке сақталды" : "Тауар каталогқа қосылды"); }
  function toggle(id: number, field: "workspace" | "agents" | "marketplace") { const product = products.find((item) => item.id === id); if (!product) return; const value = !product[field]; setProducts(products.map((item) => item.id === id ? { ...item, [field]: value } : item)); if (supabase && companyId) { const column = field === "workspace" ? "workspace_active" : field === "agents" ? "agent_visible" : "marketplace_published"; void supabase.from("products").update({ [column]: value }).eq("id", id); } }
  if (!registered) return <Registration onSubmit={saveCompany} onDemo={() => { localStorage.setItem("alsat-company", "1"); setRegistered(true); }} />;
  return <main className="shell"><aside className="sidebar"><Brand /><Link className="agent-switch" href="/agent">↗ СӨ кабинетін көру</Link><div className="role-links"><Link href="/dispatcher">Экспедитор кабинеті</Link><Link href="/warehouse">Қойма менеджері</Link></div><nav>{nav.map(n => <button key={n.id} className={screen === n.id ? "nav active" : "nav"} onClick={() => setScreen(n.id)}><i>{n.icon}</i>{n.label}</button>)}</nav><div className="sidebar-foot"><span className="avatar">А</span><div><strong>Alsat Company</strong><small>Компания әкімшісі</small></div></div></aside><section className="content"><header><div><p className="eyebrow">ALSAT WORKSPACE</p><h1>{screen === "home" ? "Қайырлы күн, Alsat" : nav.find(n => n.id === screen)?.label}</h1></div><button className="bell" onClick={() => setNotice("Жаңа хабарлама жоқ. Барлық дерек синхрондалды.")} aria-label="Хабарламалар">⌁</button></header>{notice && <div className="toast">✓ {notice}<button onClick={() => setNotice("")}>×</button></div>}{screen === "home" && <Dashboard products={products} stock={totalStock} onAdd={() => setScreen("create")} onOrders={() => setScreen("orders")} />}{screen === "products" && <Products products={products} onAdd={() => setScreen("create")} onToggle={toggle} />}{screen === "create" && <ProductForm onSubmit={addProduct} onCancel={() => setScreen("products")} />}{screen === "agents" && <Agents products={agentProducts} />}{screen === "orders" && <Orders products={agentProducts} />}{screen === "commissions" && <Commissions products={products} />}</section><nav className="mobile-nav">{nav.slice(0, 4).map(n => <button key={n.id} className={screen === n.id ? "active" : ""} onClick={() => setScreen(n.id)}><i>{n.icon}</i>{n.label}</button>)}</nav><div className="supabase-status">{isSupabaseConfigured ? "● Supabase қосылған" : "○ Demo режимі"}</div></main>;
}
function Brand(){ return <div className="brand"><span>А</span><b>alsat</b><em>workspace</em></div> }
function Registration({onSubmit,onDemo}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onDemo:()=>void}) { return <main className="registration"><section className="register-copy"><Brand /><div><p className="eyebrow">ALSAT WORKSPACE</p><h1>Сатуды бір жерден басқарыңыз</h1><p>Компания, каталог, сауда өкілдері және тапсырыстар — бір ыңғайлы workspace-та.</p></div><div className="feature-list"><span>✓ Тауарларды СӨ-ге бөлек ашу</span><span>✓ Marketplace-ке саналы жариялау</span><span>✓ Мобильді сауда ағыны</span></div></section><section className="register-card"><div><p className="eyebrow">1 / 1 ҚАДАМ</p><h2>Компанияны тіркеу</h2><p>Workspace-ыңызды бірнеше минутта ашыңыз.</p></div><form onSubmit={onSubmit}><label>Компания атауы<input required placeholder="Мысалы, Alsat Company" name="company" /></label><div className="two"><label>БСН<input placeholder="123456789012" name="bin" /></label><label>Қала<input required placeholder="Алматы" name="city" /></label></div><label>Байланыс телефоны<input required placeholder="+7 700 000 00 00" name="phone" /></label><button className="primary full">Workspace ашу <span>→</span></button></form><button className="demo-entry" onClick={onDemo}>Demo Workspace-қа кіру →</button><small>Тіркелу арқылы Alsat платформасының шарттарымен келісесіз.</small></section></main> }
function Dashboard({products, stock, onAdd, onOrders}:{products:Product[];stock:number;onAdd:()=>void;onOrders:()=>void}) { return <><div className="page-actions"><p>Компанияңыздың бүгінгі көрсеткіштері.</p><button className="primary" onClick={onAdd}>+ Тауар қосу</button></div><div className="stats"><Stat label="Белсенді тауарлар" value={String(products.filter(p=>p.workspace).length)} detail="Workspace каталогында" icon="▦"/><Stat label="Сауда өкілдері" value="4" detail="3 белсенді" icon="◉"/><Stat label="Бүгінгі тапсырыстар" value="8" detail={money.format(428500)} icon="▤"/><Stat label="Қоймадағы тауар" value={String(stock)} detail="бірлік" icon="□"/></div><div className="grid"><section className="card activity"><div className="card-title"><div><h3>Соңғы тапсырыстар</h3><p>Бүгінгі белсенділік</p></div><button className="link" onClick={onOrders}>Барлығын көру</button></div><OrderRow name="Дүкен «Арман»" sum="98 400 ₸" status="Жаңа"/><OrderRow name="ЭлектроМаркет" sum="165 000 ₸" status="Жиналуда"/><OrderRow name="Құрылыс KZ" sum="44 700 ₸" status="Жеткізілді"/></section><section className="card launch"><p className="eyebrow">ЖЫЛДАМ ӘРЕКЕТ</p><h3>Каталогыңызды іске қосыңыз</h3><p>Тауарды қосып, сауда өкілдеріне қолжетімді етіңіз.</p><button className="white-button" onClick={onAdd}>Тауар қосу →</button></section></div></> }
function Stat({label,value,detail,icon}:{label:string;value:string;detail:string;icon:string}){return <section className="stat"><span className="stat-icon">{icon}</span><p>{label}</p><strong>{value}</strong><small>{detail}</small></section>}
function OrderRow({name,sum,status}:{name:string;sum:string;status:string}){return <div className="order-row"><span className="order-icon">▤</span><div><strong>{name}</strong><small>Бүгін, 11:40</small></div><div><b>{sum}</b><span className={'badge '+status}>{status}</span></div></div>}
function Products({products,onAdd,onToggle}:{products:Product[];onAdd:()=>void;onToggle:(id:number,f:"workspace"|"agents"|"marketplace")=>void}) { return <><div className="page-actions"><p>Ішкі каталог, СӨ және Marketplace көрінуін бөлек басқарыңыз.</p><button className="primary" onClick={onAdd}>+ Тауар қосу</button></div><section className="card product-card"><div className="table-head"><span>Тауар</span><span>Бағасы</span><span>Қойма</span><span>Көрінуі</span></div>{products.map(p=><article className="product-row" key={p.id}><div className="product-name"><span className="product-thumb">▦</span><div><strong>{p.name}</strong><small>{p.sku} · Комиссия {p.commission}%</small></div></div><b>{money.format(p.price)}</b><span>{p.stock} бірл.</span><div className="visibility"><Toggle label="Workspace" value={p.workspace} onChange={()=>onToggle(p.id,"workspace")}/><Toggle label="СӨ" value={p.agents} onChange={()=>onToggle(p.id,"agents")}/><Toggle label="Market" value={p.marketplace} onChange={()=>onToggle(p.id,"marketplace")}/></div></article>)}</section></> }
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:()=>void}){ return <button onClick={onChange} className={value?"toggle yes":"toggle"}><i></i>{label}</button> }
function ProductForm({onSubmit,onCancel}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onCancel:()=>void}) { return <section className="form-page"><div className="page-actions"><div><button className="back" onClick={onCancel}>← Тауарлар</button><h2>Жаңа тауар</h2><p>Тауардың сату арналары үшін параметрлерді реттеңіз.</p></div></div><form className="product-form" onSubmit={onSubmit}><section className="card form-card"><h3>Негізгі ақпарат</h3><label>Тауар атауы<input required name="name" placeholder="Мысалы, Кабель ВВГнг 3×2.5" /></label><div className="two"><label>Артикул<input required name="sku" placeholder="VVG-325" /></label><label>Қоймадағы саны<input required type="number" min="0" name="stock" placeholder="0" /></label></div><div className="two"><label>Бағасы, ₸<input required type="number" min="0" name="price" placeholder="0" /></label><label>СӨ комиссиясы, %<input required type="number" min="0" max="100" name="commission" placeholder="5" /></label></div></section><section className="card form-card channels"><div><h3>Көріну және жариялау</h3><p>Әр арнаны жеке қосыңыз.</p></div><label className="channel"><input type="checkbox" name="workspace" defaultChecked/><span><strong>Workspace-та белсенді</strong><small>Компанияның ішкі каталогында көрінеді.</small></span></label><label className="channel"><input type="checkbox" name="agents" defaultChecked/><span><strong>Сауда өкілдеріне көрсету</strong><small>СӨ каталогынан тапсырыс жинауға болады.</small></span></label><label className="channel"><input type="checkbox" name="marketplace"/><span><strong>Marketplace-те жариялау</strong><small>Ашық marketplace каталогына бөлек шығарылады.</small></span></label></section><div className="form-actions"><button type="button" onClick={onCancel}>Болдырмау</button><button className="primary" type="submit">Тауарды сақтау →</button></div></form></section> }
function Agents({products}:{products:Product[]}){const [adding,setAdding]=useState(false);const [agents,setAgents]=useState([{name:"Мақсат Ержанұлы",city:"Алматы",orders:24,commission:"184 500 ₸"},{name:"Аружан Сәрсенова",city:"Астана",orders:17,commission:"132 300 ₸"}]);const [carted,setCarted]=useState(false);const addAgent=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);setAgents([...agents,{name:String(data.get("name")),city:String(data.get("city")),orders:0,commission:"0 ₸"}]);setAdding(false)};return <><div className="page-actions"><p>СӨ мобильді каталогында {products.length} тауар қолжетімді.</p><button className="primary" onClick={()=>setAdding(true)}>+ Сауда өкілін қосу</button></div>{adding&&<form className="card action-form" onSubmit={addAgent}><h3>Жаңа сауда өкілі</h3><label>Аты-жөні<input name="name" required/></label><label>Қала<input name="city" required/></label><div className="form-actions"><button type="button" onClick={()=>setAdding(false)}>Болдырмау</button><button className="primary" type="submit">Қосу</button></div></form>}<div className="agent-grid">{agents.map((agent,index)=><section className="card agent-profile" key={agent.name}><span className={index%2?"avatar large blue":"avatar large"}>{agent.name[0]}</span><h3>{agent.name}</h3><p>{agent.city} · Белсенді</p><div><b>{agent.orders}</b><small>тапсырыс</small><b>{agent.commission}</b><small>комиссия</small></div></section>)}</div><section className="card mobile-preview"><div><p className="eyebrow">СӨ MOBILE FLOW</p><h3>Компания → Дүкен → Тауар → Тапсырыс</h3><p>Сауда өкілі телефоннан компания каталогын ашып, дүкенге тапсырыс жинайды.</p></div><div className="phone"><b>Alsat</b><span>Дүкен «Арман»</span><small>{products[0]?.name ?? "Тауар жоқ"}</small><button onClick={()=>setCarted((value)=>!value)}>{carted?"✓ Себетте":"Себетке қосу"}</button></div></section></>}
function Orders({products}:{products:Product[]}){const sum=useMemo(()=>products.slice(0,2).reduce((n,p)=>n+p.price,0),[products]);const [adding,setAdding]=useState(false);const [orders,setOrders]=useState<Array<{name:string;sum:string;status:string}>>([{name:"Дүкен «Арман»",sum:money.format(sum||98400),status:"Жаңа"},{name:"ЭлектроМаркет",sum:"165 000 ₸",status:"Жиналуда"},{name:"Құрылыс KZ",sum:"44 700 ₸",status:"Жеткізілді"}]);const addOrder=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);setOrders([{name:String(data.get("store")),sum:money.format(Number(data.get("sum"))),status:"Жаңа"},...orders]);setAdding(false)};return <><div className="page-actions"><p>Дүкендерден түскен тапсырыстарды бақылаңыз.</p><button className="primary" onClick={()=>setAdding(true)}>+ Жаңа тапсырыс</button></div>{adding&&<form className="card action-form" onSubmit={addOrder}><h3>Жаңа тапсырыс</h3><label>Дүкен<input name="store" required/></label><label>Сома<input name="sum" type="number" min="1" required/></label><div className="form-actions"><button type="button" onClick={()=>setAdding(false)}>Болдырмау</button><button className="primary" type="submit">Сақтау</button></div></form>}<section className="card order-list">{orders.map((order,index)=><OrderRow key={`${order.name}-${index}`} name={order.name} sum={order.sum} status={order.status}/>)}</section></>}
function Commissions({products}:{products:Product[]}){const rate=products.length?Math.round(products.reduce((n,p)=>n+p.commission,0)/products.length):0;return <><div className="page-actions"><p>Сауда өкілдерінің орындалған сатылымдары үшін есеп.</p></div><div className="stats"><Stat label="Есептелген комиссия" value="316 800 ₸" detail="Осы ай" icon="₸"/><Stat label="Орташа мөлшерлеме" value={rate+"%"} detail="Каталог бойынша" icon="%"/></div><section className="card commission"><h3>Төлемге дайын</h3><OrderRow name="Мақсат Ержанұлы" sum="184 500 ₸" status="Расталды"/><OrderRow name="Аружан Сәрсенова" sum="132 300 ₸" status="Расталды"/></section></>}
