export type ProductVariantOption = {
  name: string;
  values: string[];
};

export type ProductCatalogItem = {
  id: string | number;
  name: string;
  sku: string;
  price: number;
  purchasePrice?: number;
  salePrice?: number;
  wholesalePrice?: number;
  stock: number;
  commission: number;
  workspace: boolean;
  agents: boolean;
  marketplace: boolean;
  category?: string;
  subcategory?: string;
  brand?: string;
  manufacturer?: string;
  model?: string;
  barcode?: string;
  barcodeType?: string;
  description?: string;
  bulletPoints?: string[];
  searchTerms?: string;
  countryOfOrigin?: string;
  unit?: string;
  currency?: string;
  vatRate?: number;
  minOrder?: number;
  maxOrder?: number;
  reorderPoint?: number;
  warehouseLocation?: string;
  weightKg?: number;
  lengthCm?: number;
  widthCm?: number;
  heightCm?: number;
  packageQuantity?: number;
  shippingClass?: string;
  warrantyMonths?: number;
  condition?: string;
  certification?: string;
  dangerousGoods?: boolean;
  hasVariants?: boolean;
  variantOptions?: ProductVariantOption[];
  attributes?: Record<string, string>;
  imageUrl?: string;
  imageUrls?: string[];
  marketplaceTitle?: string;
  marketplaceDescription?: string;
};
